# https://taskfile.dev

version: '3'

tasks:
  default:
    - task: fmt
    - go build -ldflags="-s -w"
    - task: lint

  install:
    - task: fmt
    - go install -ldflags="-s -w"
    - task: lint

  fmt:
    - goimports -w -l .
    - gofumpt -w -l .

  lint:
    - go vet ./...
