// generated by goclap; DO NOT EDIT

package main

import (
	"os"

	"github.com/steverusso/goclap/clap"
)

func (*mycli) UsageHelp() string {
	return `mycli - Print a string with a prefix

usage:
   mycli [options] [input]

options:
   -prefix  <arg>   The value to prepend to the input string [$MY_PREFIX]
   -count  <arg>    Print the output this many extra times [$MY_COUNT]
   -h               Show this help message

arguments:
   [input]   The user provided input [$MY_INPUT]`
}

func (c *mycli) Parse(args []string) {
	if len(args) > 0 && len(args) == len(os.Args) {
		args = args[1:]
	}

	cc := clap.NewCommandParser("mycli")
	cc.CustomUsage = c.UsageHelp
	cc.Flag("prefix", clap.NewString(&c.prefix)).Env("MY_PREFIX")
	cc.Flag("count", clap.NewUint(&c.count)).Env("MY_COUNT")
	cc.Arg("[input]", clap.NewString(&c.input)).Env("MY_INPUT")
	cc.Parse(args)
}
