// generated by goclap; DO NOT EDIT

package main

import "github.com/steverusso/goclap/clap"

func (*mycli) UsageHelp() string {
	return `mycli - Print a string with the option to make it uppercase

usage:
   mycli [options] <input>

options:
   -upper   Make the input string all uppercase
   -h       Show this help message

arguments:
   <input>   The input string`
}

func (c *mycli) Parse(args []string) {
	p := clap.NewCommandParser("mycli")
	p.CustomUsage = c.UsageHelp
	p.Flag("upper", clap.NewBool(&c.toUpper))
	p.Arg("<input>", clap.NewString(&c.input)).Require()
	p.Parse(args)
}
