// generated by goclap; DO NOT EDIT

package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/steverusso/goclap/clap"
)

func (*mycli) usage() string {
	return `mycli - Print a string with the option to make it uppercase

usage:
   mycli [options] <input>

options:
   -upper   Make the input string all uppercase
   -h       Show this help message

arguments:
   <input>   The input string`
}

func (c *mycli) parse(args []string) {
	if len(args) > 0 && len(args) == len(os.Args) {
		args = args[1:]
	}

	var err error

	f := flag.FlagSet{Usage: func() {}}
	f.Var(clap.NewBool(&c.toUpper), "upper", "")
	if err = f.Parse(args); err != nil {
		if err == flag.ErrHelp {
			fmt.Println(c.usage())
			os.Exit(0)
		}
		fmt.Fprintf(os.Stderr, "error: %v.\nRun 'mycli -h' for usage.", err)
		os.Exit(2)
	}

	rest := f.Args()
	if len(rest) < 1 {
		fmt.Fprintf(os.Stderr, "error: missing arg <input>")
		os.Exit(2)
	}
	if err = clap.NewString(&c.input).Set(rest[0]); err != nil {
		fmt.Fprintf(os.Stderr, "error: parsing arg: %v\n", err)
	}
}
