// generated by goclap; DO NOT EDIT

package main

import (
	"errors"
	"fmt"
	"os"
	"strconv"
	"strings"
)

func claperr(format string, a ...any) {
	format = "\033[1;31merror:\033[0m " + format
	fmt.Fprintf(os.Stderr, format, a...)
}

type clapParser struct {
	usg  func(to *os.File)
	args []string
	idx  int

	optName  string
	optEqVal string
	optHasEq bool
}

func (p *clapParser) exitUsgGood() {
	p.usg(os.Stdout)
	os.Exit(0)
}

func (p *clapParser) exitMissingArg(name string) {
	claperr("not enough args: no \033[1;33m%s\033[0m provided\n", name)
	p.usg(os.Stderr)
	os.Exit(1)
}

func (p *clapParser) stageOpt() bool {
	if p.optName != "" {
		p.idx++
	}
	if p.idx > len(p.args)-1 {
		p.optName = ""
		return false
	}
	arg := p.args[p.idx]
	if arg[0] != '-' {
		p.optName = ""
		return false
	}
	arg = arg[1:]
	if arg == "" {
		claperr("emtpy option ('-') found\n")
		os.Exit(1)
	}
	if arg[0] == '-' {
		arg = arg[1:]
	}
	if arg == "" {
		p.idx++
		p.optName = ""
		return false
	}

	p.optEqVal = ""
	if eqIdx := strings.IndexByte(arg, '='); eqIdx != -1 {
		p.optName = arg[:eqIdx]
		if eqIdx < len(arg) {
			p.optEqVal = arg[eqIdx+1:]
		}
		p.optHasEq = true
	} else {
		p.optName = arg
		p.optHasEq = false
	}
	return true
}

func (p *clapParser) nextStr() string {
	if p.optName != "" {
		if p.optHasEq {
			return p.optEqVal
		}
		if p.idx == len(p.args)-1 {
			claperr("option '%s' needs an argument\n", p.optName)
			os.Exit(1)
		}
		p.idx++
		return p.args[p.idx]
	}
	p.idx++
	return p.args[p.idx-1]
}

func (p *clapParser) exitBadInput(typ string, err error) {
	var forWhat string
	switch {
	case p.optName != "":
		forWhat = "option '" + p.optName + "'"
	default:
		forWhat = "argument"
	}
	claperr("invalid %s for %s: %v\n", typ, forWhat, err)
	os.Exit(1)
}

func (p *clapParser) thisBool() bool {
	s := p.optEqVal
	if s == "" || s == "true" || s == "1" {
		return true
	}
	if s != "false" && s != "0" {
		p.exitBadInput("bool", fmt.Errorf("%q not recognized as a boolean", s))
	}
	return false
}

func (p *clapParser) nextInt() int {
	u64, err := strconv.ParseInt(p.nextStr(), 10, 0)
	if err != nil {
		p.exitBadInput("int", errors.Unwrap(err))
	}
	return int(u64)
}

func (*strops) printUsage(to *os.File) {
	fmt.Fprintf(to, `%[1]s - perform different string operations

usage:
   %[1]s [options] <input>

options:
   -u, --upper           make the `+"`"+`input`+"`"+` string all uppercase
   -r, --reverse         reverse the final string
       --repeat  <n>     repeat the string this many times
       --prefix  <str>   add this prefix to the final string
   -h, --help            show this help message

arguments:
   <input>   the string on which to operate
`, os.Args[0])
}

func (c *strops) parse(args []string) {
	if len(args) > 0 && len(args) == len(os.Args) {
		args = args[1:]
	}
	p := clapParser{usg: c.printUsage, args: args}
	for p.stageOpt() {
		switch p.optName {
		case "upper", "u":
			c.toUpper = p.thisBool()
		case "reverse", "r":
			c.reverse = p.thisBool()
		case "repeat":
			c.repeat = p.nextInt()
		case "prefix":
			c.prefix = p.nextStr()
		case "help", "h":
			p.exitUsgGood()
		default:
			claperr("unknown option '%s'\n", p.optName)
			os.Exit(1)
		}
	}
	args = args[p.idx:]
	if len(args) < 1 {
		p.exitMissingArg("<input>")
	}

	c.input = p.nextStr()
}
