name: ci

on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.4

    - name: Build
      run: go build -v ./...

    - name: Install goimports
      run: go install golang.org/x/tools/cmd/goimports@latest

    - name: Install gofumpt
      run: go install mvdan.cc/gofumpt@latest

    - name: Format
      run: goimports -w . && gofumpt -w .

    - name: Verify
      run: |
        if [ -n "$(git diff)" ]; then
          git diff
          exit 1
        fi

    - name: Test
      run: go test -v ./...

    - name: Vet
      run: go vet -v ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: staticcheck
      run: staticcheck ./...
