name: security

on:
  workflow_dispatch:

jobs:
  vulncheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.4

    - name: Install goreportcard-cli
      run: |
        git clone https://github.com/gojp/goreportcard.git
        cd goreportcard
        make install
        go install ./cmd/goreportcard-cli

    - name: Run goreportcard-cli
      run: goreportcard-cli -v goclap/...
