name: security

on:
  schedule:
    # Run at 7am and 7pm every day.
    - cron: '0 7,19 * * *'
  workflow_dispatch:

jobs:
  vulncheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.4

    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: govulncheck
      run: govulncheck ./...
